NAME = ffhelp
DESC = FFmpeg develop help library

HEADERS = ffhelp.h                                                     

OBJS = ffmpeg.o  ffmpeg_cuvid.o  ffmpeg_filter.o  ffmpeg_hw.o ffmpeg_opt.o cmdutils.o 
